# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: connect-node-listener-azure

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: azure
  region: ${env:LOCATION}
  runtime: nodejs10
  prefix: "example"  # prefix of generated resource name
  subscriptionId: ${env:SUB_ID}

  environment: # these will be created as application settings
    SVC_BUS_QUEUE_NAME: connect-queue
    BASIC_AUTH_NAME: ${env:AUTH_NAME}
    BASIC_AUTH_PW: ${env:AUTH_PW}
    HMAC_1: ${env:HMAC}
  
      # Start of your API Management configuration
  apim:
    # API specifications
    apis:
      - name: categories-api
        subscriptionRequired: false
        # Display name
        displayName: Categories API
        # Description of API
        description: The Categories REST API
        # HTTP protocols allowed
        protocols:
          - https
        # Base path of API calls
        path: categories
        # No authorization
        authorization: none
    backends:
      - name: categories-backend
        url: api/categories
    # CORS Settings for APIM
    cors:
      allowCredentials: false
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - '*'
      exposeHeaders:
        - '*'

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  connect:
    handler: index.connectNotificationMessage
    events:
      - http: true
        authLevel: anonymous # can also be `function` or `admin`
